version: 1.0.{build}
branches:
  only:
  - appveyor-master
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\\Python35"
  github_access_token:
    secure: 8GKkrghj8KAhgmIxGneHfLGuY5V1o+Q3eptS91w4wlMh99IZi7jUefeW/IdIPKGX
  
clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    - cd c:\projects
    - git clone -q --branch=master https://github.com/swatDong/azure-sdk-for-python
    
before_build:
    - "%PYTHON%\\python.exe -m pip install --upgrade pip"
    
    - "%PYTHON%\\python.exe -m pip install pywin32-ctypes==0.0.1"
    
    - "%PYTHON%\\python.exe -m pip install cryptography"
    
    - "%PYTHON%\\python.exe -m pip install sphinx-docfx-yaml"
    - "%PYTHON%\\python.exe -m pip install sphinx --upgrade"
    - "%PYTHON%\\python.exe -m pip install sphinx_rtd_theme"
    
build:
    - cd c:\projects\azure-sdk-for-python
    - "%PYTHON%\\python.exe setup.py install"
  
on_finish:
    - cd c:\projects\azure-sdk-for-python\doc
    - call make.bat html
    - ps: Copy-Item -Path C:\projects\azure-sdk-for-python\doc\_build\html -Destination c:\projects\azure-docs-sdk-python\docs-ref-autogen -Recurse
    - cd c:\projects\azure-docs-sdk-python\docs-ref-autogen
    - dir
