version: 1.0.{build}
branches:
  only:
  - appveyor-master
skip_tags: true

environment:
  github_access_token:
    secure: 8GKkrghj8KAhgmIxGneHfLGuY5V1o+Q3eptS91w4wlMh99IZi7jUefeW/IdIPKGX
  
clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    - cd c:\projects
    - git clone -q --branch=master https://github.com/swatDong/azure-sdk-for-python
    
before_build:
    - c:\python35\python.exe -m pip install --upgrade pip
    
    # Install pywin32-ctypes 0.0.1 due to https://github.com/enthought/pywin32-ctypes/issues/60
    - c:\python35\python.exe -m pip install pywin32-ctypes==0.0.1
    
    # Install cryptography (may be 1.8.1) to avoid 'openssl' error
    - c:\python35\python.exe -m pip install cryptography
    
    # Install sphinx and its extensions
    - c:\python35\python.exe -m pip install sphinx-docfx-yaml
    - c:\python35\python.exe -m pip install sphinx --upgrade
    - c:\python35\python.exe -m pip install sphinx_rtd_theme
    
build_script:
    - cmd: >-
        cd c:\projects\azure-sdk-for-python
        c:\python35\python.exe setup.py install
  
on_finish:
    - cd c:\projects\azure-sdk-for-python\doc
    - call make.bat html
    - ps: Copy-Item -Path c:\projects\azure-sdk-for-python\doc\_build\html -Destination c:\projects\azure-docs-sdk-python\docs-ref-autogen -Recurse
    - cd c:\projects\azure-docs-sdk-python\docs-ref-autogen
    - dir
