version: 1.0.{build}
branches:
  only:
  - appveyor-master
skip_tags: true

environment:
  # Use Python 3.5
  PYTHON: "C:/Python35"
  SPHINXBUILD: "%PYTHON%/scripts/sphinx-build.exe"

  github_access_token:
    secure: 8GKkrghj8KAhgmIxGneHfLGuY5V1o+Q3eptS91w4wlMh99IZi7jUefeW/IdIPKGX

init:
    - "%PYTHON%/python.exe -m pip install --upgrade pip"

    # Install pywin32-ctypes 0.0.1 due to https://github.com/enthought/pywin32-ctypes/issues/60
    - "%PYTHON%/python.exe -m pip install pywin32-ctypes==0.0.1"

    # Install cryptography (may be 1.8.1) to avoid 'openssl' error
    - "%PYTHON%/python.exe -m pip install cryptography"

    # Install sphinx and its extensions
    - "%PYTHON%/python.exe -m pip install sphinx-docfx-yaml"
    - "%PYTHON%/python.exe -m pip install sphinx --upgrade"
    - "%PYTHON%/python.exe -m pip install sphinx_rtd_theme"

clone_script:
    - git config --global core.autocrlf true
    - git config core.autocrlf
    - cd c:/projects
    - git clone -q --branch=master https://github.com/swatDong/azure-sdk-for-python

install:
    - cd c:/projects/azure-sdk-for-python
    
    # Ignore STDOUT
    - "%PYTHON%/python.exe setup.py install > null"

build: off

on_success:
    - cd c:/projects/azure-sdk-for-python/doc

    # TODO: generate yml and copy to c:/projects/azure-docs-sdk-python/docs-ref-autogen
    - call make.bat html
    - ps: Copy-Item -Path c:/projects/azure-sdk-for-python/doc/_build/html -Destination c:/projects/azure-docs-sdk-python/docs-ref-autogen -Recurse

    - git config --global credential.helper store
    - ps: ac "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - cd c:/projects/azure-docs-sdk-python
    - git status
    - git config --global user.name "swatDong"
    - git config --global user.email "09122swat@gmail.com"
    - git add .
    - git commit -a -m "appveyor ci - update yml files"

    # TODO: to master branch
    - git push -u origin appveyor-master -f
